environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "111"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\ci\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV% python --version"
  - "%CMD_IN_ENV% conda update -q conda"
  - "%CMD_IN_ENV% conda install conda-build anaconda-client"
  - "%CMD_IN_ENV% conda install --yes numpy scipy matplotlib"
  - "%CMD_IN_ENV% conda install --yes --channel matsci spglib"
  - "%CMD_IN_ENV% pip install -r requirements.txt"
  - "%CMD_IN_ENV% pip install pybtex nose sympy unittest2 coverage ase coveralls"

build: false

test_script:
  - "%CMD_IN_ENV% python setup.py develop"
  - "%CMD_IN_ENV% nosetests"

notifications:
  - provider: Email
    to:
      - shyuep@gmail.com
on_finish:
- ps: $env:Path -split ";"
